hint "Begin Trigger Track"; 
sleep 1; 
player setPos (getMarkerPos "Respawn_West"); 
player allowDamage false; 
sleep 2; 
player setPos (getPos EWS1); 
EWS1 setDamage 1; 
sleep 5; 
EWS2 setDamage 1; 
sleep 10; 
player setPos (getPos AA1); 
sleep 3; 
AA1 setDamage 1; 
sleep 5; 
AA2 setDamage 1; 
sleep 5; 
AA3 setDamage 1; 
sleep 5; 
AA4 setDamage 1; 
sleep 10; 
player setPos (getPos CV1); 
CV1 setDamage 1; 
sleep 5; 
CV2 setDamage 2; 
sleep 5; 
CV3 setDamage 3; 
sleep 5; 
player setPos (getMarkerPos "Rgp"); 
Action1= player addAction ["See Jet 1", {player setPos (getMarkerPos "QRF_JetPos1")}]; 
Action2= player addAction ["See Jet 2", {player setPos (getMarkerPos "QRF_JetPos2")}]; 
Action3= player addAction ["Return To Thirsk", {player setPos (getMarkerPos "Thirsk")}]; 
hint "Sleeping 120 Seconds"; 
sleep 60; 
hint "Sleeping for 60 more seconds"; 
sleep 60; 
player removeAction Action1; 
player removeAction Action2; 
player removeAction Action3; 
hint "False Triggering Win of City in 3 seconds."; 
sleep 3;
['','A3M_fnc_AssaultDone',True,False] spawn BIS_fnc_MP;